finalised installer

diff --git a/tetris b/tetris
--- a/tetris
+++ b/tetris
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-die()
+die ()
 {
     printf '%s\n' "$@"
     exit 1
@@ -13,14 +13,14 @@ if (( ${BASH_VERSINFO[0]} == 4 && ${BASH_VERSINFO[1]} < 3 )); then
     die 'Incorrect Bash version. Requires 4.3 or later'
 fi
 
-extrap()
+extrap ()
 {
     stty sane
     tput cvvis
 }
 trap extrap EXIT
 
-showHelp()
+showHelp ()
 {
     # TODO allow moving replay files
     # Display horizontal line
@@ -45,7 +45,7 @@ ____HELP
     exit 0
 }
 
-uninstallTetris()
+uninstallTetris ()
 {
     local password
 
@@ -72,15 +72,14 @@ uninstallTetris()
     exit 0
 }
 
-checkTerminalSize()
+checkTerminalSize ()
 {
-    local               \
-        boxWidth        \
-        maxWidth=41     \
-        maxHeight=23    \
-        termWidth       \
-        x               \
-        y
+    local -- boxWidth
+    local -- maxWidth=41
+    local -- maxHeight=23
+    local -- termWidth
+    local -- x
+    local -- y
 
     (( $( tput cols ) > $maxWidth && $( tput lines ) > $maxHeight )) && return
 
@@ -142,18 +141,28 @@ checkTerminalSize()
 
 debugMode=0
 replayFile=
+
 while getopts ":h :u :r: :x" arg; do
     case $arg in
-        h)  showHelp;;
-        u)  uninstallTetris;;
-        r)  if test -s "$OPTARG"; then
-                replayFile="$OPTARG"
-            else
-                die "$OPTARG is not a file"
-            fi;;
-        x)  debugMode=1;;
-        \?) die "Invalid option -$OPTARG";;
-        \:) die "Option -$OPTARG requires a parameter";;
+        (h) {
+            showHelp
+        };;
+        (u) {
+            uninstallTetris
+        };;
+        (r) {
+            [[ -s "$OPTARG" ]] || die "$OPTARG is not a file"
+            replayFile="$OPTARG"
+        };;
+        (x) {
+            debugMode=1
+        };;
+        (\?) {
+            die "Invalid option -$OPTARG"
+        };;
+        (\:) {
+            die "Option -$OPTARG requires a parameter"
+        };;
     esac
 done
 
diff --git a/tetris-install b/tetris-install
--- a/tetris-install
+++ b/tetris-install
@@ -1,25 +1,30 @@
 #!/bin/bash
 
-# if [[ "$UID" != "0" ]]; then
-#     printf "Your password is required to install this game.
-#             \rLeave blank to cancel install.
-#             \rRun as root if you don't have a password."
-#     while true; do
-#         IFS= read -sp "> " password
-#         [[ -z "$password" ]] && exit 0
+if ! [[ -s ./tetris ]]; then
+    printf "Please cd to into the extracted/pulled tetris folder"
+    exit 1
+fi
 
-#         if $( echo "$password" | sudo -Svp "" ); then
-#             break
-#         fi
-#     done
-#     doSudo="sudo"
-# else
-#     doSudo=
-# fi
+if [[ "$UID" != "0" ]]; then
+    printf "Your password is required to install this game.
+            \rLeave blank to cancel install.
+            \rRun as root if you don't have a password.\n"
+    while true; do
+        IFS= read -sp "> " password
+        [[ -z "$password" ]] && exit 0
 
-logDir="/var/games/tetris"
-replayDir="/var/games/tetris/replays"
-installDir="/usr/local/"
+        if $( echo "$password" | sudo -Svp "" ); then
+            break
+        fi
+    done
+    doSudo="sudo"
+else
+    doSudo=
+fi
+
+rootDir="/var/games/tetris"
+replayDir="${rootDir}/replays"
+installDir="/usr/local/bin/tetris"
 
 while true; do
     printf '\n%s\n%s\n' "Where would you like to install Tetris?" "Default is ${installDir}"
@@ -29,6 +34,14 @@ while true; do
 
     [[ "${path:0:1}" == "~" ]] && path="${HOME}${path:1}"
     [[ "${path:0:1}" != "/" ]] && path="${PWD}/${path:0}"
+
+    if [[ "$path" =~ [\#\%\&\{\}\\\<\>\*\?\/\$\!\'\"\:\@\+\`\|\=] ]]; then
+        echo "Path contains an illegal character"
+        continue
+    elif [[ "$path" =~ [\ \n\t\v] ]]; then
+        echo "It is advisable to not have whitespace in the path"
+        continue
+    fi
 
     if [[ -d "$path" ]]; then
         if ! [[ -w "$path" ]]; then
@@ -50,13 +63,20 @@ while true; do
     done
 
     if $( mkdir -p $path ); then
-        echo ""
+        echo
         break
     fi
 
 done
 
-# $doSudo mkdir -p "$replayDir" 2>/dev/null
-# $doSudo chmod -R o+wr "$logDir"
+$doSudo mkdir -vp {"$replayDir","$installDir"} 2>/dev/null
+$doSudo chmod -vR o+rw "$rootDir"
+$doSudo cp -vr ./{tetris,tetris-game,Assets} "$installDir"
+$doSudo chmod -vR o+rwx "$installDir"
+
+if ! [[ " ${PATH//:/ } " =~ " ${installDir} " ]]; then
+    printf "\nPlease put the following line into your ${HOME}/.bashrc or other profile script\n"
+    echo "export PATH=\$PATH:${installDir}"
+fi
 
 printf "\nTetris installed.\n\n"
